Repository datasciencecampus/bus-metrics-england, pull requests merged in 2024-01, with the labels that each got.

#2 Initial docs
  .flake8
  .github/ISSUE_TEMPLATE/bug_report_template.md
  .github/ISSUE_TEMPLATE/feature_request_template.md
  .github/code_review_template.md
  .github/pull_request_template.md
  .github/workflows/.gitkeep
  .pre-commit-config.yaml
  .pydocstyle
  .python-version
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  LICENSE
  README.md
  requirements.txt
Labels: Priority: Critical, documentation

#7 Ci config
  .github/workflows/codecov.yml
  pyproject.toml
  setup.py
  src/bus_metrics/setup/README.md
  src/bus_metrics/setup/ingest.toml
  src/bus_metrics/setup/ingest_realtime_data.py
  src/bus_metrics/setup/ingest_static_data.py
  tests/setup/test_RealtimeDataIngest.py
  tests/setup/test_StaticDataIngest.py
Labels: chore

#5 4 scripts to ingest all required data
  .github/workflows/codecov.yml
  .gitignore
  README.md
  data/realtime/.gitkeep
  data/resources/.gitkeep
  data/timetable/.gitkeep
  log/.gitkeep
  pyproject.toml
  requirements.txt
  setup.py
  src/bus_metrics/setup/README.md
  src/bus_metrics/setup/ingest.toml
  src/bus_metrics/setup/ingest_realtime_data.py
  src/bus_metrics/setup/ingest_static_data.py
  tests/data/.gitkeep
  tests/data/BODS_API_message
  tests/setup/test_RealtimeDataIngest.py
  tests/setup/test_StaticDataIngest.py
Labels: enhancement
